apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-{{ .Values.environment }}
  namespace: argocd
spec: 
  generators:
  - git:
      repoURL: https://github.com/oliver2401/monitoring.git
      revision: main
      files:
        - path: "apps/*/{{ .Values.environment }}/values.yaml"
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{ "{{path[1]}}" }}'
    spec:
      project: monitoring-{{ .Values.environment }}
      source:
        repoURL: https://github.com/oliver2401/monitoring.git
        targetRevision: main
        path: '{{ "{{path}}" }}'
        helm:
          valueFiles:
          - ../values.default.yaml
          - values.yaml
      destination:
        name: "in-cluster"
        namespace: "monitoring-{{ .Values.environment }}"
      syncPolicy:
        syncOptions:
            - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true            
